- id: '1541529151466'
  alias: Start HomeKit two minutes after Home Assistant startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:02
  - service: homekit.start
- id: '1543318981512'
  alias: Rolläden nach Sonnenuntergang schließen
  trigger:
  - event: sunset
    offset: +00:30:00
    platform: sun
  condition: []
  action:
  - alias: ''
    data: {}
    service: cover.close_cover
- id: '1543319953830'
  alias: Rollläden wochentags um 05:30 Uhr öffnen
  trigger:
  - at: 05:30:00
    platform: time
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: cover.open_cover
- id: '1543319953831'
  alias: Rollläden wochenends um 09:00 Uhr öffnen
  trigger:
  - at: 09:00:00
    platform: time
  condition:
  - condition: time
    weekday:
      - sat
      - sun 
  action:
  - service: cover.open_cover
